title: "Ariane Neumann"
description: "Bioinformatic student at LU, previous Infection Medicine researcher, podcast host"
theme: jekyll-theme-hacker 

# Optional
# logo: /assets/img/profile.jpg
show_downloads: false
google_analytics:
